# Generated by Django 5.0.6 on 2024-06-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_alter_carrito_comprador_carrito_alter_libro_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='foto',
            field=models.ImageField(null=True, upload_to='img', verbose_name='Imagen'),
        ),
    ]
