# Generated by Django 5.0.6 on 2024-06-22 01:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_alter_libro_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.AddField(
            model_name='libro',
            name='best_seler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='libro',
            name='subtipo',
            field=models.CharField(choices=[('Ficción', [('Sci-fi', 'Sci-fi'), ('Misterio', 'Misterio'), ('Terror', 'Terror')]), ('No_Ficción', [('Historia', 'Historia'), ('Biografía', 'Biografía')]), ('Sin subtipo', 'Sin Subtipo')], default='Sin subtipo', max_length=40),
        ),
        migrations.AddField(
            model_name='libro',
            name='tipo',
            field=models.CharField(choices=[('Ficción', 'No_Ficción'), ('Sin tipo', 'Sin tipo'), ('No Ficción', 'No Ficción')], default='Sin tipo', max_length=30),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('Entregado', 'Entregado'), ('En proceso', 'En proceso'), ('Cancelado', 'Cancelado')], default='En proceso', max_length=40),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(default='no hay direccion', max_length=60),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
