# Generated by Django 5.0.6 on 2024-06-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_remove_usuario_nombre_libro_best_seler_libro_subtipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='nombre_autor',
            field=models.CharField(default='no posee autor', max_length=50),
        ),
        migrations.AlterField(
            model_name='libro',
            name='tipo',
            field=models.CharField(choices=[('No Ficción', 'No Ficción'), ('Sin tipo', 'Sin tipo'), ('Ficción', 'No_Ficción')], default='Sin tipo', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('Entregado', 'Entregado'), ('Cancelado', 'Cancelado'), ('En proceso', 'En proceso')], default='En proceso', max_length=40),
        ),
    ]
