# Generated by Django 5.0.6 on 2024-06-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_libro_nombre_autor_alter_libro_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='tipo',
            field=models.CharField(choices=[('Ficción', 'Ficción'), ('Sin tipo', 'Sin tipo'), ('No Ficción', 'No Ficción')], default='Sin tipo', max_length=30),
        ),
    ]
