# Generated by Django 5.0.6 on 2024-06-26 21:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0012_alter_libro_tipo_alter_pedido_estado_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='comprador_carrito',
        ),
        migrations.AddField(
            model_name='pedido',
            name='comprador_pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.usuario'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='comprador_carrito',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.usuario'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.libro'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='tipo',
            field=models.CharField(choices=[('No_Ficción', 'No_Ficción'), ('Sin tipo', 'Sin tipo'), ('Ficción', 'Ficción')], default='Sin tipo', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('Cancelado', 'Cancelado'), ('En proceso', 'En proceso'), ('Entregado', 'Entregado')], default='En proceso', max_length=40),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.libro')),
            ],
        ),
        migrations.DeleteModel(
            name='Detalle_pedido',
        ),
    ]
