# Generated by Django 5.0.6 on 2024-06-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0020_alter_libro_tipo_alter_pedido_estado_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='tipo',
            field=models.CharField(choices=[('Sin tipo', 'Sin tipo'), ('No_Ficción', 'No_Ficción'), ('Ficción', 'Ficción')], default='Sin tipo', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('Entregado', 'Entregado'), ('En proceso', 'En proceso'), ('Cancelado', 'Cancelado')], default='En proceso', max_length=40),
        ),
    ]
