# Generated by Django 5.0.6 on 2024-06-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0021_alter_libro_tipo_alter_pedido_estado_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='tipo',
            field=models.CharField(choices=[('Sin tipo', 'Sin tipo'), ('Ficción', 'Ficción'), ('No_Ficción', 'No_Ficción')], default='Sin tipo', max_length=30),
        ),
    ]
