# Generated by Django 5.0.6 on 2024-06-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0022_alter_libro_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='En proceso', max_length=40),
        ),
    ]
